# based on ubuntu
FROM node:18

# update apt list
RUN apt update

# install tools
RUN apt install -y udev

# create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
# COPY . .

EXPOSE 80 1433

CMD [ "npm", "start" ]